#!/bin/sh

dir_path=$1
dirs=`find $dir_path -name index.html`

for dir in $dirs;
do
    #echo -n  $dir
    echo -n `sed "s/<[^>]*>//g" $dir |wc -w`
    echo -n " words"
    echo -n " =>  "
    echo   $dir
    #echo " Words"
done
